---
{{- if not (eq .Values.clusterName "local-cluster") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "work-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "work-manager.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "work-manager.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}